name: DivineBanItem
main: com.divinebanitem.DivineBanItem
version: 1.0.0
api-version: '1.20'
author: DivineBanItem
softdepend: [Vault]
commands:
  dbi:
    description: DivineBanItem 主指令
    usage: /<command> help
    aliases: [divinebanitem]
permissions:
  divinebanitem.use:
    description: 基础指令权限
    default: true
  divinebanitem.reload:
    description: 重载配置与语言
    default: op
  divinebanitem.nbt:
    description: 查询手持物品 NBT
    default: op
  divinebanitem.buy:
    description: 购买许可
    default: true
  divinebanitem.admin:
    description: 管理员指令
    default: op
  divinebanitem.bypass.*:
    description: 绕过全部封禁
    default: op
